# Generated by Django 4.2.7 on 2023-11-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default='BOT', max_length=20),
        ),
    ]
