# Generated by Django 4.2.7 on 2023-11-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_author_comment_post_associated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
